# Generated by Django 4.1.7 on 2023-03-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey_api', '0002_commentsdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentsDB',
            new_name='CommentDB',
        ),
    ]
