# Generated by Django 4.1.7 on 2023-03-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey_api', '0003_rename_commentsdb_commentdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdb',
            name='image',
            field=models.ImageField(upload_to='uploadPhotos'),
        ),
    ]
