# Generated by Django 4.1.7 on 2023-03-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey_api', '0004_alter_postdb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
