# Generated by Django 4.1.7 on 2023-04-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey_api', '0006_postdb_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdb',
            name='image',
        ),
        migrations.AddField(
            model_name='postdb',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
