# Generated by Django 4.1.7 on 2023-04-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey_api', '0007_remove_postdb_image_postdb_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
