# docker-compose.dev.yml
#########################################
# The "development" compose file builds 
# the images locally
#########################################

version: "3.9"
services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=$DEBUG
      - PARK_API_KEY=xBbZChwMOwiRzaLjWde5q4gIYFWnGAz8NG2Pvw1L
  nginx:
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    ports:
      - "80:80"
